# Generated by Django 4.2.18 on 2025-03-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stations", "0005_connectingstation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_SERVICE", "In Service"),
                            ("DELAYED", "Delayed"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("OUT_OF_SERVICE", "Out of Service"),
                        ],
                        default="IN_SERVICE",
                        max_length=20,
                    ),
                ),
                ("has_ac", models.BooleanField(default=False)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("HELWAN", "Helwan"),
                            ("MARG", "El-Marg"),
                            ("SHOBRA", "Shobra El Kheima"),
                            ("MONIB", "El-Monib"),
                            ("ADLY", "Adly Mansour"),
                            ("KIT_KAT", "Kit Kat"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "camera_car_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_trains",
                        to="stations.station",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trains",
                        to="stations.line",
                    ),
                ),
                (
                    "next_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upcoming_trains",
                        to="stations.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_SERVICE", "In Service"),
                            ("DELAYED", "Delayed"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("OUT_OF_SERVICE", "Out of Service"),
                        ],
                        default="IN_SERVICE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_schedules",
                        to="stations.station",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="trains.train",
                    ),
                ),
            ],
            options={
                "ordering": ["arrival_time"],
            },
        ),
        migrations.CreateModel(
            name="TrainCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_number", models.PositiveIntegerField()),
                ("has_camera", models.BooleanField(default=False)),
                ("current_passengers", models.PositiveIntegerField(default=0)),
                (
                    "crowd_level",
                    models.CharField(
                        choices=[
                            ("EMPTY", "Empty"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("FULL", "Full"),
                        ],
                        default="EMPTY",
                        max_length=20,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="trains.train",
                    ),
                ),
            ],
            options={
                "ordering": ["car_number"],
                "unique_together": {("train", "car_number")},
            },
        ),
        migrations.AddIndex(
            model_name="train",
            index=models.Index(
                fields=["train_number"], name="trains_trai_train_n_34b2bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="train",
            index=models.Index(
                fields=["line", "status"], name="trains_trai_line_id_1cbd44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="train",
            index=models.Index(
                fields=["current_station"], name="trains_trai_current_a486a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["arrival_time"], name="trains_sche_arrival_b0b7fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["station", "arrival_time"],
                name="trains_sche_station_74b613_idx",
            ),
        ),
    ]
