# Generated by Django 4.2.18 on 2025-02-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="train_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique numeric identifier for the train",
                max_length=10,
                unique=True,
            ),
        ),
    ]
