# .pre-commit-config.yaml

# Repositories that contain hooks
# repos:
#   # Black: Code formatter for Python
#   - repo: https://github.com/psf/black
#     rev: 23.3.0
#     hooks:
#       - id: black
#         args: ['--line-length=88']  # Customize the line length here if needed

#   # Flake8: Linter for Python
#   - repo: https://github.com/PyCQA/flake8
#     rev: 6.0.0
#     hooks:
#       - id: flake8
#         args:
#           - --max-line-length=88  # Customize the max line length if needed
        # additional_dependencies:
        #   - flake8-bugbear  # Optional: Adds additional linting checks
        #   - flake8-docstrings  # Optional: Adds docstring linting checks

  # Isort: Sorts imports alphabetically and automatically separates them into sections
  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: v5.12.0  # Use the latest valid version
  #   hooks:
  #     - id: isort
  #       args: ['--profile=black']  # Align with Black's formatting style
  #       additional_dependencies:
  #         - isort[app]  # Optional: Install extra dependencies for app-specific sorting

  # Pydocstyle: Checks compliance with Python docstring conventions
  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: 6.1.1
  #   hooks:
  #     - id: pydocstyle
  #       args:
  #         - --convention=google  # Use the Google style for docstrings (customize as needed)
