# Render configuration file for deploying a Django application to Render

services:
  - type: web
    name: egypt-metro
    dockerfilePath: ./docker/Dockerfile
    runtime: python
    region: frankfurt                 # Adjust based on your location
    plan: free
    buildCommand: >
      apt-get update && apt-get install -y gcc libpq-dev python3-dev &&
      pip install --upgrade pip &&
      pip install poetry &&
      poetry install --no-dev &&  
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput
    startCommand: "gunicorn egypt_metro.wsgi:application --bind 0.0.0.0:8000 --workers=3 --threads=2 --timeout=120"
    envVars:
      - key: ENVIRONMENT             # Environment for loading specific config
        value: prod
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: ALLOWED_HOSTS
        value: https://backend-54v5.onrender.com
      - key: DEBUG
        value: "False"
    disk:                            # Persistent storage (optional)
      name: persistent-data
      mountPath: /var/lib/egypt-metro
      sizeGB: 1
    healthCheckPath: "/health"       # Optional, ensure health endpoint exists
