services:
  - type: web
    name: egypt-metro
    env: python
    region: frankfurt                 # Adjust based on your location
    rootDirectory: backend          # Root directory of the project
    plan: free
    buildCommand: 
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - python manage.py collectstatic --noinput
      - python manage.py migrate --noinput
    startCommand: "gunicorn egypt_metro.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: ENVIRONMENT             # Environment for loading specific config
        value: prod
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: CORS_ALLOW_ALL_ORIGINS   # Set CORS settings
        value: "True"
    disk:                            # Persistent storage (optional)
      name: persistent-data
      mountPath: /var/lib/egypt-metro
      sizeGB: 1
    secretFiles:
      - path: /etc/secrets/env.prod  # Load sensitive secrets (e.g., SECRET_KEY, JWT_SECRET)
    healthCheckPath: "/health"       # Optional, ensure health endpoint exists
