# Generated by Django 4.2.18 on 2025-02-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_connectingstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_stations', models.ManyToManyField(help_text='Stations that are connected through this interchange.', related_name='connected_interchanges', to='stations.station')),
                ('station', models.ForeignKey(help_text='The station that serves as an interchange.', on_delete=django.db.models.deletion.CASCADE, related_name='interchanges', to='stations.station')),
            ],
            options={
                'verbose_name': 'Interchange',
                'verbose_name_plural': 'Interchanges',
            },
        ),
    ]
