# Generated by Django 4.2.18 on 2025-02-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_interchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectingstation',
            name='lines',
        ),
        migrations.RemoveField(
            model_name='connectingstation',
            name='station',
        ),
        migrations.RemoveField(
            model_name='interchange',
            name='connected_stations',
        ),
        migrations.RemoveField(
            model_name='interchange',
            name='station',
        ),
        migrations.AddIndex(
            model_name='line',
            index=models.Index(fields=['name'], name='stations_li_name_aad62f_idx'),
        ),
        migrations.AddIndex(
            model_name='linestation',
            index=models.Index(fields=['line', 'order'], name='stations_li_line_id_fa633b_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['name'], name='stations_st_name_1d3a22_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['latitude', 'longitude'], name='stations_st_latitud_ba98b4_idx'),
        ),
        migrations.DeleteModel(
            name='ConnectingStation',
        ),
        migrations.DeleteModel(
            name='Interchange',
        ),
    ]
