# Generated by Django 4.2.18 on 2025-02-14 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_remove_connectingstation_lines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_time', models.IntegerField(default=3, help_text='Average transfer time in minutes')),
                ('lines', models.ManyToManyField(related_name='connecting_stations', to='stations.line')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connecting_station', to='stations.station')),
            ],
            options={
                'indexes': [models.Index(fields=['station'], name='stations_co_station_2f57c0_idx')],
            },
        ),
    ]
