# Generated by Django 4.2.18 on 2025-02-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
    ]
