# Generated by Django 4.2.18 on 2025-02-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_precomputedroute_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precomputedroute',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='precomputedroute',
            name='duration',
        ),
        migrations.AddField(
            model_name='precomputedroute',
            name='interchanges',
            field=models.JSONField(blank=True, help_text='List of interchanges with corresponding lines', null=True),
        ),
    ]
