# Generated by Django 4.2.18 on 2025-02-13 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_interchange'),
        ('routes', '0002_remove_precomputed_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField(default=0, help_text='Total distance in meters')),
                ('total_time', models.IntegerField(default=0, help_text='Estimated time in minutes')),
                ('path', models.JSONField(default=list, help_text='Ordered list of stations and lines in the route')),
                ('interchanges', models.JSONField(blank=True, default=list, help_text='List of interchange points', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='stations.station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='stations.station')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.DeleteModel(
            name='PrecomputedRoute',
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['start_station', 'end_station'], name='routes_rout_start_s_31e1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['created_at'], name='routes_rout_created_31febf_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_active'], name='routes_rout_is_acti_d0dc30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('start_station', 'end_station')},
        ),
    ]
