# Generated by Django 4.2.18 on 2025-02-09 17:43

import apps.routes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_connectingstation'),
        ('routes', '0003_remove_precomputedroute_distance_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='precomputedroute',
            name='routes_prec_start_s_d2a4df_idx',
        ),
        migrations.AlterUniqueTogether(
            name='precomputedroute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='precomputedroute',
            name='line',
            field=models.ForeignKey(default=apps.routes.models.get_default_line, on_delete=django.db.models.deletion.CASCADE, to='stations.line'),
        ),
        migrations.AlterUniqueTogether(
            name='precomputedroute',
            unique_together={('start_station', 'end_station', 'line')},
        ),
        migrations.AddIndex(
            model_name='precomputedroute',
            index=models.Index(fields=['start_station', 'end_station', 'line'], name='routes_prec_start_s_4ecefc_idx'),
        ),
    ]
