# Generated by Django 4.2.18 on 2025-02-13 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_interchange'),
        ('routes', '0003_route_delete_precomputedroute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='number_of_stations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='primary_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_routes', to='stations.line'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['primary_line'], name='routes_rout_primary_b88cf2_idx'),
        ),
    ]
