# Generated by Django 5.1.3 on 2024-12-05 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{14}$", "National ID must be exactly 14 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(0|20|\\+20)\\d{9,10}$",
                        "Phone number must start with '0', '20', or '+20', followed by 9-10 digits.",
                    )
                ],
            ),
        ),
    ]
