# Generated by Django 5.1.3 on 2024-12-05 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^01\\d{9}$', "Phone number must start with '01' followed by 9 digits.")]),
        ),
    ]
