# Generated by Django 4.2.18 on 2025-02-24 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_subscription_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="14-digit national identification number",
                max_length=14,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{14}$", "National ID must be exactly 14 digits."
                    )
                ],
            ),
        ),
    ]
