# Generated by Django 4.2.18 on 2025-02-26 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_fix_user_fields_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="14-digit national identification number",
                max_length=14,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{14}$", "National ID must be exactly 14 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Egyptian phone number format: 01XXXXXXXXX",
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^01[0-9]{9}$",
                        "Phone number must start with 01 and be 11 digits long.",
                    )
                ],
            ),
        ),
    ]
