# Generated by Django 4.2.18 on 2025-02-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_national_id_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CREDIT_CARD", "Credit Card"), ("WALLET", "Digital Wallet")],
                help_text="Preferred payment method",
                max_length=20,
                null=True,
            ),
        ),
    ]
