# Generated by Django 4.2.18 on 2025-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_stationzone_subscriptionplan_usersubscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="upgrade_required",
            field=models.BooleanField(
                default=False, help_text="Indicates ticket to be upgraded"
            ),
        ),
    ]
