# Generated by Django 4.2.18 on 2025-04-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0005_connectingstation"),
        ("tickets", "0003_ticket_upgrade_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="upgrade_required",
        ),
        migrations.AddField(
            model_name="ticket",
            name="needs_upgrade",
            field=models.BooleanField(
                default=False, help_text="Flag indicating this ticket needs upgrading"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="temp_exit_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temp_ticket_exits",
                to="stations.station",
            ),
        ),
    ]
