# Generated by Django 4.2.18 on 2025-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tickets",
            "0004_remove_ticket_upgrade_required_ticket_needs_upgrade_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="covered_zones",
            field=models.JSONField(
                blank=True,
                help_text="Specific zone numbers covered by this subscription",
                null=True,
            ),
        ),
    ]
