# Generated by Django 4.2.18 on 2025-05-02 02:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("CREDIT_CARD", "Credit Card"),
                            ("DEBIT_CARD", "Debit Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_WALLET", "Mobile Wallet"),
                            ("CASH", "Cash"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("card_last4", models.CharField(blank=True, max_length=4)),
                ("card_brand", models.CharField(blank=True, max_length=20)),
                (
                    "card_expiry_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "card_expiry_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current wallet balance",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Wallet",
                "verbose_name_plural": "User Wallets",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAW", "Withdrawal"),
                            ("PAYMENT", "Payment"),
                            ("REFUND", "Refund"),
                            ("TICKET_PURCHASE", "Ticket Purchase"),
                            ("SUBSCRIPTION_PURCHASE", "Subscription Purchase"),
                            ("TICKET_UPGRADE", "Ticket Upgrade"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "related_object_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="wallet.paymentmethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.userwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userwallet",
            index=models.Index(fields=["user"], name="wallet_user_idx"),
        ),
        migrations.AddIndex(
            model_name="userwallet",
            index=models.Index(fields=["is_active"], name="wallet_active_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user"], name="transaction_user_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["wallet"], name="transaction_wallet_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["type"], name="transaction_type_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="transaction_status_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["created_at"], name="transaction_date_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["related_object_type", "related_object_id"],
                name="transaction_related_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(fields=["user"], name="payment_method_user_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(fields=["payment_type"], name="payment_method_type_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["is_default"], name="payment_method_default_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(fields=["is_active"], name="payment_method_active_idx"),
        ),
    ]
