# Generated by Django 4.2.18 on 2025-06-07 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0005_usersubscription_covered_zones"),
        ("stations", "0005_connectingstation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ticket_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subscription_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("tickets_scanned", models.PositiveIntegerField(default=0)),
                ("subscriptions_used", models.PositiveIntegerField(default=0)),
                ("total_entries", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Daily Analytics",
                "verbose_name_plural": "Daily Analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TicketUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "revenue_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_usages",
                        to="stations.line",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_usages",
                        to="stations.station",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="tickets.ticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "revenue_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_usages",
                        to="stations.line",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_usages",
                        to="stations.station",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="tickets.usersubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ticket_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subscription_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("tickets_scanned", models.PositiveIntegerField(default=0)),
                ("subscriptions_used", models.PositiveIntegerField(default=0)),
                ("total_entries", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="stations.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ticket_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subscription_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("tickets_scanned", models.PositiveIntegerField(default=0)),
                ("subscriptions_used", models.PositiveIntegerField(default=0)),
                ("total_entries", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="stations.line",
                    ),
                ),
            ],
        ),
    ]
