# Generated by Django 4.2.18 on 2025-06-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_usersubscription_covered_zones"),
        ("stations", "0005_connectingstation"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketusagerecord",
            name="usage_type",
            field=models.CharField(
                choices=[("ENTRY", "Entry"), ("EXIT", "Exit")],
                default="ENTRY",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticketusagerecord",
            unique_together={("ticket", "station", "usage_type")},
        ),
    ]
