# This is a GitHub Actions workflow file that deploys a Django app to Render.
#  .github/workflows/django.yaml

name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install Dependencies
      run: |
        poetry install

    - name: Export requirements.txt for Deployment
      run: |
        poetry export --without-hashes -o requirements.txt

    - name: Install Render CLI
      run: |
        npm install -g render-cli
        echo 'export PATH="$PATH:$(npm bin -g)"' >> $GITHUB_ENV
        echo "Render CLI installation complete."

    - name: Verify Render CLI Installation
      run: |
        echo "Verifying Render CLI"
        render --version  # Check if render command works

    - name: Deploy to Render
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "Starting deployment to Render..."
        render deploy --config render.yaml --service-name egypt-metro
        echo "Deployment complete!"
